dist: xenial

sudo: required

services:
  - docker

env:
  matrix:
    - VARIANT=test
    - VARIANT=docker

language: python
python:
  - "3.6"

install:
  - >
    if [ "${VARIANT}" = "test" ]; then
      pip install black
      pip install -r requirements.txt
    fi

script:
  - >
    if [ "${VARIANT}" = "test" ]; then
      python -m compileall .
      black --check *.py config/*.py

    elif  [ "${VARIANT}" = "docker" ]; then
      image="djmelik/lndash"

      docker build --no-cache -t "${image}:latest" .

      travis_retry timeout 5m echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin

      docker push "${image}:latest"

      if [ -n "${TRAVIS_TAG}" ]; then
        docker tag "${image}:latest" "${image}:${TRAVIS_TAG}"
        docker push "${image}:${TRAVIS_TAG}"
      fi
    fi
